### ISSUE TITLE
Plugin not loading

### ISSUE THREAD

**Issue by Paniramix** [InventivetalentDev/AdvancedSlabs#6]
[00:41:01] [Server thread/INFO]: This server is running Paper version git-Paper-784 (MC: 1.10) (Implementing API version 1.10-R0.1-SNAPSHOT)
........
[00:38:13] [Server thread/INFO]: [AdvancedSlabs] Enabling AdvancedSlabs v1.6.0
[00:38:13] [Server thread/INFO]: [ReflectionHelper] Version is v1_10_R1 (11001)
[00:38:13] [Server thread/ERROR]: Error occurred while enabling AdvancedSlabs v1.6.0 (Is it up to date?)
java.lang.NullPointerException
        at org.inventivetalent.advancedslabs.EntityManager.<init>(EntityManager.java:56) ~[?:?]
        at org.inventivetalent.advancedslabs.AdvancedSlabs.onEnable(AdvancedSlabs.java:155) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:292) ~[patched_1.10.jar:git-Paper-784]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:319) [patched_1.10.jar:git-Paper-784]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:407) [patched_1.10.jar:git-Paper-784]
        at org.bukkit.craftbukkit.v1_10_R1.CraftServer.loadPlugin(CraftServer.java:358) [patched_1.10.jar:git-Paper-784]
        at org.bukkit.craftbukkit.v1_10_R1.CraftServer.enablePlugins(CraftServer.java:318) [patched_1.10.jar:git-Paper-784]
        at net.minecraft.server.v1_10_R1.MinecraftServer.t(MinecraftServer.java:414) [patched_1.10.jar:git-Paper-784]
        at net.minecraft.server.v1_10_R1.MinecraftServer.l(MinecraftServer.java:379) [patched_1.10.jar:git-Paper-784]
        at net.minecraft.server.v1_10_R1.MinecraftServer.a(MinecraftServer.java:333) [patched_1.10.jar:git-Paper-784]
        at net.minecraft.server.v1_10_R1.DedicatedServer.init(DedicatedServer.java:274) [patched_1.10.jar:git-Paper-784]
        at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:580) [patched_1.10.jar:git-Paper-784]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]
[00:38:13] [Server thread/INFO]: [AdvancedSlabs] Disabling AdvancedSlabs v1.6.0
[00:38:13] [Server thread/INFO]: [AdvancedSlabs] Saving data...

**Comment by InventivetalentDev** [comment]
There are these things called pastebin or `code tags`. Please upload the errors to pastebin and provide ALL details requested in the template.
