### ISSUE TITLE
Failed to load path

### ISSUE THREAD

**Issue by MrNessuno** [InventivetalentDev/AdvancedSlabs#9]
## What steps will reproduce the problem?  
1.  Spigot server 1.10 (latest on Server.pro)
2.  place AdvancedSlabs block
3. restast server

## What were you expecting to happen? What happened instead?  
I see slabs heads instead of block and i can't remove or edit, i can just kill slabs to remove them.
## What version of the plugin are you using? *Type /version &lt;Plugin Name&gt;*  
1.7.2
## What Spigot version are you using? *Type /version*  
1.10
## What plugins ae you using? *Type /plugins*  
Plugins (10): VerticalRails, WorldEdit, CraftBook, CreeperHeal, UltraCosmetics, PacketListenerApi, WirelessRedstone, AdvancedSlabs, MapManager, AnimatedFrames
## Do you have an error log? Use [pastebin.com](http://pastebin.com). *If you're not sure, upload your whole server log*  
[21:00:48 WARN]: [AdvancedSlabs] Task #20 for AdvancedSlabs v1.7.2 generated an exception java.lang.RuntimeException: Failed to load paths at org.inventivetalent.advancedslabs.AdvancedSlabs.loadPaths(AdvancedSlabs.java:384) ~[?:?] at org.inventivetalent.advancedslabs.AdvancedSlabs$2.run(AdvancedSlabs.java:208) ~[?:?] at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftTask.run(CraftTask.java:71) ~[spigot-1.10.jar:git-Spigot-6016ac7-10c10b3] at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350) [spigot-1.10.jar:git-Spigot-6016ac7-10c10b3] at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:741) [spigot-1.10.jar:git-Spigot-6016ac7-10c10b3] at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:399) [spigot-1.10.jar:git-Spigot-6016ac7-10c10b3] at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:672) [spigot-1.10.jar:git-Spigot-6016ac7-10c10b3] at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:571) [spigot-1.10.jar:git-Spigot-6016ac7-10c10b3] at java.lang.Thread.run(Thread.java:745) [?:1.8.0_72] Caused by: java.lang.IllegalStateException: This is not a JSON Array. at com.google.gson.JsonElement.getAsJsonArray(JsonElement.java:106) ~[spigot-1.10.jar:git-Spigot-6016ac7-10c10b3] at org.inventivetalent.advancedslabs.AdvancedSlabs.loadPaths(AdvancedSlabs.java:381) ~[?:?] 
... 8 more
## Did your client crash? *Upload errors in .minecraft/logs/latest.log as well*  
No

##Before and after server restart screenshots:
![2016-07-22_22 05 26](https://cloud.githubusercontent.com/assets/20603088/17069761/99bdb922-5058-11e6-8118-1bd71e70ca83.png)
![2016-07-22_22 06 21](https://cloud.githubusercontent.com/assets/20603088/17069762/99bf4170-5058-11e6-8150-ff8bec7f64fc.png)

**Comment by InventivetalentDev** [comment]
Your server didn't save the data correctly. Please try to delete the data folder (/plugins/AdvancedSlabs) and try again.

**Comment by MrNessuno** [comment]
I tried to do that, but when i restart again I have the same error.
I also tried to use /aslab save and when I restarted the server /aslab reload or respawn but nothing changed.

**Comment by fer112233** [comment]
Exactly same issue as MrNessuno
